name: Status check function
on: [push]

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: sleep 20
      - name: Runs on failure
        # This is a status check which will return true if any of the previous steps failed
        if: failure()
        run: echo "Job failed"
      - name: Runs on success
        # This is a status check which will return true if all of the previous steps passed
        # Note that 'success()' is not actually needed as it is the default behaviour
        if: success()
        run: echo "Job passed"
      - name: Always runs
        # This is a status check which will always return true (even if workflow cancelled)
        if: always()
        run: echo "Job finished"
      - name: Runs on cancelled
        # This is a status check which will return true if the workflow was cancelled
        if: cancelled()
        run: echo "Job cancelled"
  job-2:
    runs-on: ubuntu-latest
    needs: job-1
    if: failure()
    steps:
      - name: Step 1
        run: echo "Job 2 failed"
