name: Workflow commands
on: [push]
jobs:
  testing-wf-commands:
    runs-on: ubunutu-latest
    steps:
      - name: Setting an error message
        run: echo "::error::Missing semicolon
      - name: Setting an error message with params
        run: echo "::error title=Error title, title file=app.js,line=2,endline=3,col=5,endColumn=7::Missing semicolon"
      - name: Setting a debug message with params
        run: echo "::debug title=Debug title, title file=app.js,line=2,endline=3,col=5,endColumn=7::Missing semicolon"
      - name: Setting a warning message with params
        run: echo "::warning title=Warning title, title file=app.js,line=2,endline=3,col=5,endColumn=7::Missing semicolon"
      - name: Setting a notice message with params
        run: echo "::notice title=Notice title, title file=app.js,line=2,endline=3,col=5,endColumn=7::Missing semicolon"
