# It is worth noting that workflow runs only allows 3 levels of nesting
# This means that you can't have a workflow run inside a workflow run inside a workflow run
# But can have a workflow run inside a workflow run inside a workflow
name: Workflow run
on:
  workflow_run:
    workflows: ["Repo events"]
    types: [completed]
    branches:
      - main

jobs:
  echo-string:
    runs-on: ubuntu-latest
    steps:
      - name: Echo string
        run: echo "Hello, world!"
